import { StoryObj } from '@storybook/react';
declare const meta: {
    component: (props: import('./index').Props) => import("react/jsx-runtime").JSX.Element;
    title: string;
    tags: string[];
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const LargeTitleL: Story;
export declare const LargeTitleM: Story;
export declare const LargeTitleS: Story;
export declare const TitleL1: Story;
export declare const TitleM1: Story;
export declare const TitleS1: Story;
export declare const TitleL2: Story;
export declare const TitleM2: Story;
export declare const TitleS2: Story;
export declare const TitleL3: Story;
export declare const TitleM3: Story;
export declare const TitleS3: Story;
export declare const CalloutL: Story;
export declare const CalloutM: Story;
export declare const CalloutS: Story;
export declare const HeadlineL: Story;
export declare const HeadlineM: Story;
export declare const HeadlineS: Story;
export declare const BodyL: Story;
export declare const BodyM: Story;
export declare const BodyS: Story;
export declare const SubheadlineL: Story;
export declare const SubheadlineM: Story;
export declare const SubheadlineS: Story;
export declare const FootnoteL: Story;
export declare const FootnoteM: Story;
export declare const FootnoteS: Story;
export declare const CaptionL1: Story;
export declare const CaptionM1: Story;
export declare const CaptionS1: Story;
export declare const CaptionL2: Story;
export declare const CaptionM2: Story;
export declare const CaptionS2: Story;
