name: Create GitHub Release with Changelog (Conventional Commits)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Changelog
        id: changelog
        run: |
          CHANGELOG=$(git log --pretty=format:"%s" $(git describe --tags --abbrev=0 HEAD^)..HEAD | grep -E '^(feat|fix|chore|docs|refactor|style|test|perf)(\(.+\))?: ' || true)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            📚 [View Storybook](https://ashenoooone.github.io/wishary-ui-kit/)

            ## What's Changed
            ${{ env.CHANGELOG }}
          draft: true
